name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Clean frontend node_modules and lockfile
        run: |
          rm -rf frontend/node_modules frontend/package-lock.json
      - name: Reinstall frontend deps
        run: npm --prefix frontend install
      # - name: Generate sitemap
      #   run: node tools/generate-sitemap.js
      - name: Build frontend
        run: npm --prefix frontend run build

  smoke-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run smoke test
        # This may fail in CI if backend requires envs; keep allowed-failure optional
        run: node tools/smoke-test-backend.js
        continue-on-error: true
